apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "mcp.lifeishao.com/v1alpha1",
          "kind": "MCPServer",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "mcp-server-k8s-operator"
            },
            "name": "mcpserver-sample"
          },
          "spec": {
            "args": [],
            "command": "docker",
            "env": [
              {
                "name": "GITHUB_PERSONAL_ACCESS_TOKEN",
                "valueFrom": {
                  "secretKeyRef": {
                    "key": "GITHUB_TOKEN",
                    "name": "github-secrets"
                  }
                }
              }
            ],
            "image": "ghcr.io/github/github-mcp-server",
            "name": "github-mcp-server-01",
            "transport": "stdio"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-05-10T01:15:01Z"
    operators.operatorframework.io/builder: operator-sdk-v1.39.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: mcp-server-k8s-operator.v0.0.5
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MCPServer is the Schema for the mcpservers API.
      displayName: MCPServer
      kind: MCPServer
      name: mcpservers.mcp.lifeishao.com
      version: v1alpha1
  description: A Kubernetes Operator for managing MCP Servers
  displayName: MCP Server Kubernetes Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - mcp.lifeishao.com
          resources:
          - mcpservers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - mcp.lifeishao.com
          resources:
          - mcpservers/finalizers
          verbs:
          - update
        - apiGroups:
          - mcp.lifeishao.com
          resources:
          - mcpservers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: mcp-server-k8s-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: mcp-server-k8s-operator
          control-plane: controller-manager
        name: mcp-server-k8s-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                image: howlowck/mcp-server-k8s-operator:v0.0.5
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: mcp-server-k8s-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: mcp-server-k8s-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - mcp
  - mcp-servers
  - management
  links:
  - name: Mcp Server K8s Operator
    url: https://mcp-server-k8s-operator.domain
  maintainers:
  - email: 338265+howlowck@users.noreply.github.com
    name: Hao
  maturity: alpha
  provider:
    name: lifeishao.com
  version: 0.0.5
