apiVersion: mcp.hub.docker.com/v1alpha1
kind: MCPServer
metadata:
  labels:
    app.kubernetes.io/name: mcp-server-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: mcpserver-sample
spec:
  # TODO(user): Add fields here
