apiVersion: mcp.lifeishao.com/v1alpha1
kind: MCPServer
metadata:
  labels:
    app.kubernetes.io/name: mcp-server-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: mcpserver-sample
spec:
  transport: "stdio"
  name: "github-mcp-server-01"
  command: "docker" # supports "docker", "uvx", "npx"
  image: "ghcr.io/github/github-mcp-server"
  args: []
  env:
    - name: GITHUB_PERSONAL_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-secrets
          key: GITHUB_TOKEN
  